# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: halmo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhalmo.proto\"\x8e\x01\n\x07Message\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\x07.StatusH\x00\x12\x15\n\x04move\x18\x02 \x01(\x0b\x32\x05.MoveH\x00\x12\x15\n\x04game\x18\x03 \x01(\x0b\x32\x05.GameH\x00\x12\x19\n\x06player\x18\x04 \x01(\x0b\x32\x07.PlayerH\x00\x12\x17\n\x05lobby\x18\x05 \x01(\x0b\x32\x06.LobbyH\x00\x42\x06\n\x04type\"8\n\x06Status\x12\x19\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0b.StatusCode\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"0\n\x04Move\x12\x14\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x06.Coord\x12\x12\n\x02to\x18\x02 \x01(\x0b\x32\x06.Coord\"\x1d\n\x05\x43oord\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"F\n\x04Game\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0enumber_players\x18\x02 \x01(\x05\x12\x18\n\x07players\x18\x03 \x03(\x0b\x32\x07.Player\"\x16\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x05Lobby\x12\x18\n\x07players\x18\x01 \x03(\x0b\x32\x07.Player\x12\x14\n\x05games\x18\x02 \x03(\x0b\x32\x05.Game*\x1f\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'halmo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSCODE._serialized_start=452
  _STATUSCODE._serialized_end=483
  _MESSAGE._serialized_start=16
  _MESSAGE._serialized_end=158
  _STATUS._serialized_start=160
  _STATUS._serialized_end=216
  _MOVE._serialized_start=218
  _MOVE._serialized_end=266
  _COORD._serialized_start=268
  _COORD._serialized_end=297
  _GAME._serialized_start=299
  _GAME._serialized_end=369
  _PLAYER._serialized_start=371
  _PLAYER._serialized_end=393
  _LOBBY._serialized_start=395
  _LOBBY._serialized_end=450
# @@protoc_insertion_point(module_scope)
