#!/usr/bin/env bash
set -euo pipefail
main(){
    >&2 echo "[+]  generating loader... ⚙️"
    ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    cat <<\EOF >"$ROOT/../app/loader.lua"
--[[
--
-- Halmö
--
-- (c) 2015-2023 Younis Bensalah <younis.bensalah@gmail.com>
--
--]]

-- Code generated by scripts/gen-loader.sh
EOF
    for file in $(find $ROOT/../app/src/{ui,core} -type f -name '*.lua'); do
        class="$(basename "$file" .lua)"
        pkg="$(basename $(dirname "$file"))"
        printf '%s = require "%s.%s"\n' "$class" "$pkg" "$class" \
                >>"$ROOT/../app/loader.lua"
        >&2 echo "[*]  $class ✅"
    done
    >&2 echo "[+]  loader is ready! 🦄"
}
main "$@"
